export enum eRole {
  SYSTEM_ADMIN = 'SYSTEM_ADMIN',
  SUB_SYSTEM_ADMIN = "SUB_SYSTEM_ADMIN",
  STATISTICS_ADMIN = 'STATISTICS_ADMIN',
  ORDERS_ADMIN = 'ORDERS_ADMIN',
  APPROVERS_ADMIN = "APPROVERS_ADMIN",
  SYSTEM_INFO_ADMIN = 'SYSTEM_INFO_ADMIN'
}